const actionTypes = {
  ADD_EXPENSE: "ADD_EXPENSE",
  REMOVE_EXPENSE: "REMOVE_EXPENSE",
  ITEM_QUANTITY_UPDATE: "ITEM_QUANTITY_UPDATE",
  ITEM_VALUE_UPDATE: "ITEM_VALUE_UPDATE",
  ITEM_NAME_UPDATE: "ITEM_NAME_UPDATE",
  FORM_WARNING: "FORM_WARNING"
};

export default actionTypes;
